#pragma once
#include <stdint.h>

enum PX4_CUSTOM_MAIN_MODE {
	PX4_CUSTOM_MAIN_MODE_MANUAL = 1,    // CD5C5C (IndianRed)
	PX4_CUSTOM_MAIN_MODE_ALTCTL,        // D2691E (Chocolate)
	PX4_CUSTOM_MAIN_MODE_POSCTL,        // HAS SUB MODES
	PX4_CUSTOM_MAIN_MODE_AUTO,          // HAS SUB MODES
	PX4_CUSTOM_MAIN_MODE_ACRO,          // FF69B4 (HotPink)
	PX4_CUSTOM_MAIN_MODE_OFFBOARD,      // FFFF00 (Yellow)
	PX4_CUSTOM_MAIN_MODE_STABILIZED,    // CD5C5C (IndianRed)
	PX4_CUSTOM_MAIN_MODE_RATTITUDE_LEGACY,  // FFFFFF (White)
	PX4_CUSTOM_MAIN_MODE_SIMPLE,        // FFFFFF (White)
	PX4_CUSTOM_MAIN_MODE_TERMINATION,   // FFFFFF (White)
};

enum PX4_CUSTOM_SUB_MODE_AUTO {
	PX4_CUSTOM_SUB_MODE_AUTO_READY = 1, // 00FF8F (SpringGreen)
	PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF,   // FFA07A (LightSalmon)
	PX4_CUSTOM_SUB_MODE_AUTO_LOITER,    // FF8C00 (DarkOrange)
	PX4_CUSTOM_SUB_MODE_AUTO_MISSION,   // 00FF00 (Green)
	PX4_CUSTOM_SUB_MODE_AUTO_RTL,       // 00FFFF (Cyan)
	PX4_CUSTOM_SUB_MODE_AUTO_LAND,      // FFA500 (Orange)
	PX4_CUSTOM_SUB_MODE_AUTO_RESERVED_DO_NOT_USE,  // FFFFFF (White)
	PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET,     // 98FB98 (PaleGreen)
	PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND,  // FFFFFF (White)
	PX4_CUSTOM_SUB_MODE_AUTO_VTOL_TAKEOFF,    // FFFFFF (White)
	PX4_CUSTOM_SUB_MODE_EXTERNAL1,     
	PX4_CUSTOM_SUB_MODE_EXTERNAL2,
	PX4_CUSTOM_SUB_MODE_EXTERNAL3,   
	PX4_CUSTOM_SUB_MODE_EXTERNAL4,
	PX4_CUSTOM_SUB_MODE_EXTERNAL5,
	PX4_CUSTOM_SUB_MODE_EXTERNAL6,
	PX4_CUSTOM_SUB_MODE_EXTERNAL7,
	PX4_CUSTOM_SUB_MODE_EXTERNAL8,
};

enum PX4_CUSTOM_SUB_MODE_POSCTL {
	PX4_CUSTOM_SUB_MODE_POSCTL_POSCTL = 0, // 0000FF (Blue)
	PX4_CUSTOM_SUB_MODE_POSCTL_ORBIT,      // A020F0 (Purple)
	PX4_CUSTOM_SUB_MODE_POSCTL_SLOW        // 9370DB (MediumPurple)
};

union px4_custom_mode {
	struct {
		uint16_t reserved;
		uint8_t main_mode;
		uint8_t sub_mode;
	};
	uint32_t data;
	float data_float;
	struct {
		uint16_t reserved_hl;
		uint16_t custom_mode_hl;
	};
};